services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapii

    build:
      context: .
      dockerfile: ./Dockerfile

    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=db;Database=Books;User=sa;Password=password123!;MultipleActiveResultSets=true

    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=password123!"
      - "ACCEPT_EULA=Y"
    container_name: mssql
    ports:
      - "1433:1433"